### ISSUE TITLE
analyze_rna_seq.scala fails while compiling script

### ISSUE THREAD

**Issue by shassathe** [YeoLab/gscripts#73]
I am running the rna seq pipeline on C.Elegans RNA-Seq datasets. I keep getting an error while the pipeline compiles the QScript:

```
Compiling 1 QScript 
ERROR 11:04:51,874 QScriptManager - analyze_rna_seq.scala:295: type mismatch;
 found   : ((AnalyzeRNASeq.this.File, String, String)) => Unit
 required: ((java.io.File, String, String, String, String)) => ? 
ERROR 11:04:51,879 QScriptManager -       for (item: Tuple3[File, String, String] <- valueList) { 
ERROR 11:04:51,879 QScriptManager -                                               ^ 
ERROR 11:04:52,267 QScriptManager - one error found 
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR stack trace 
org.broadinstitute.sting.queue.QException: Compile of /home/shsathe/gscripts/qscripts/analyze_rna_seq.scala failed with 1 error
	at org.broadinstitute.sting.queue.QScriptManager.loadScripts(QScriptManager.scala:71)
	at org.broadinstitute.sting.queue.QCommandLine.org$broadinstitute$sting$queue$QCommandLine$$qScriptPluginManager(QCommandLine.scala:95)
	at org.broadinstitute.sting.queue.QCommandLine.getArgumentSources(QCommandLine.scala:227)
	at org.broadinstitute.sting.commandline.CommandLineProgram.start(CommandLineProgram.java:202)
	at org.broadinstitute.sting.commandline.CommandLineProgram.start(CommandLineProgram.java:152)
	at org.broadinstitute.sting.queue.QCommandLine$.main(QCommandLine.scala:62)
	at org.broadinstitute.sting.queue.QCommandLine.main(QCommandLine.scala)
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A GATK RUNTIME ERROR has occurred (version 2.3-1084-gd5ca5d0):
##### ERROR
##### ERROR Please check the documentation guide to see if this is a known problem
##### ERROR If not, please post the error, with stack trace, to the GATK forum
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR MESSAGE: Compile of /home/shsathe/gscripts/qscripts/analyze_rna_seq.scala failed with 1 error
##### ERROR ------------------------------------------------------------------------------------------
INFO  11:04:52,328 QCommandLine - Shutting down jobs. Please wait...

```

I am using "ce10" as the reference  genome in my manifest. Could that be an issue?

**Comment by gpratt** [comment]
My bad, I'll fix it after the encode meeting.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by gpratt** [comment]
should be fixed following commit /25aac374614e5d0313406c7004428e3d071e51e5

**Comment by Wenhao-Jin** [comment]
Hi, Gabe, I also meet the same problem. One question, maybe a little stupid: what do you mean by "commit /25aac374614e5d0313406c7004428e3d071e51e5"?

**Comment by gpratt** [comment]
Still?

Do a git pull to update your gscripts and the issue should go away.  If not
its a different issue.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by Wenhao-Jin** [comment]
Yes, it works. Thanks Gabe!

Wenhao

2015-06-04 8:51 GMT+08:00 Gabriel Pratt <notifications@github.com>:
